# Generated by Django 4.2.5 on 2023-09-14 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocol_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols_as_uploader', to=settings.AUTH_USER_MODEL),
        ),
    ]
