# Generated by Django 4.2.5 on 2023-10-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol_app', '0003_alter_protocol_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='access_level',
            field=models.CharField(choices=[('worker', 'worker'), ('manager', 'manager'), ('admin', 'admin')], default='worker', max_length=20),
        ),
    ]
