# Generated by Django 4.1.12 on 2023-10-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol_app', '0004_alter_protocol_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='beacon_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='beacon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
